site_name: HMEC Work Environments
docs_dir: src
repo_name: Work Environments
repo_url: https://github.com/HMEC-UH/work_environments

nav:
  - Welcome: index.md
  - Connect with GitHub:
    - Overview: github/index.md
    - HMEC Organization: github/hmec_org.md
  - Developing with Python:
    - Overview: python/index.md
    - Conda: python/conda.md
    - Spyder IDE: python/spyder_ide.md
    - VS Code IDE: python/vs_code_ide.md
  - Engineering with MATLAB:
    - Overview: matlab/index.md
    - WEC-Sim: matlab/wecsim.md
    - Linking w/ Python: matlab/py_linking.md    
  - Creating Great Docs:
    - Overview: mkdocs/index.md
    - Configuration: mkdocs/config.md
    - Workflow: mkdocs/workflow.md
    - Publish: mkdocs/publish.md
    
theme:
  name: material
  logo: assets/images/white_64.png
  favicon: assets/images/green_64.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: HMEC
  features:
    - navigation.tracking  # Updates URL bar dynamically as you scroll
    - navigation.indexes   # Allows folder titles to be clickable pages

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details # Optional: for collapsible blocks
  - pymdownx.superfences # Optional: for code blocks inside admonitions
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span

extra_css:
  - stylesheets/alignments.css
  - stylesheets/color_scheme.css

plugins:
  - search
  - privacy:
      links_attr_map:
        target: _blank
        rel: noopener noreferrer
